---
name: Build and Push Python Image to Google Cloud Platform Example
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_NAME: spring-test-image
      PROJECT_ID: sirup-dev
      SERVICE: spring-test # TODO: update Cloud Run service name
      REGION: asia-southeast2 # TODO: update Cloud Run service region
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

  
    - id: auth
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token' # <--
        workload_identity_provider: 'projects/152087858797/locations/global/workloadIdentityPools/sirup-dev-build/providers/sirup-dev-provider'
        service_account: 'sirup-dev-build@${{ENV.PROJECT_ID}}.iam.gserviceaccount.com'
        access_token_lifetime: '3600s' # optional, default: '3600s' (1 hour)


    - name : Setup Gcloud
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

 

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)    
      env:
        GIT_TAG: 'latest'
      run: |-
        docker tag $IMAGE_NAME:$GIT_TAG gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    - name: Docker Auth
      run: |-
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://asia-southeast2-docker.pkg.dev

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: 'latest'
      run: |-
        docker tag $IMAGE_NAME:$GIT_TAG asia-southeast2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$GIT_TAG
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$GIT_TAG
       
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}:latest
